apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for pytorch-ipex-diffusers-intel
keywords:
- pytorch
- ipex
- diffusers
- stable diffusion
name: pytorch-ipex-diffusers-intel
version: 0.1.0
